
spring:
  application:
    name: CONFIG-dev


eureka:
  instance:
    preferIpAddress: true      # Use IP of server
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka     # Use this URL to register with server
